# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - meilisearch
    ports:
      - "8080:8080"

  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch
    volumes:
      - ../meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"